apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
  namespace: mongodb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: my-app:1.2
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-svc
  namespace: mongodb
spec:
  selector:
    app: my-app
  type: NodePort
  ports:
    - name: http
      port: 3000
      nodePort: 30010
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
spec:
  defaultBackend:
    service:
      name: my-app-svc
      port:
        number: 3000
  rules:
  - host: my-app.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-app-svc
            port:
              number: 3000

    # - protocol: TCP
    #   port: 30010
    #   targetPort: 3000
    #   nodePort: 30010